services:
  arbitrage-scanner:
    build: .
    container_name: nifty-arbitrage-scanner
    restart: unless-stopped
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - PYTHONUNBUFFERED=1
      - SCAN_INTERVAL=${SCAN_INTERVAL:-600}
      - MAX_ITEMS=${MAX_ITEMS:-0}
      - MAX_SCROLLS=${MAX_SCROLLS:-400}
      - OPENSEA_API_KEY=${OPENSEA_API_KEY}
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G
    shm_size: '2gb'
    healthcheck:
      test: ["CMD", "python", "-c", "import subprocess; subprocess.run(['ps', 'aux'], check=True)"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 2m
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
